"use client";
import { useState, useEffect } from "react";
import { CreditCard, Mail, Clock3, Users, Scissors } from "lucide-react";
import type { BookingReadiness } from "@/lib/booking-readiness";
import { PaymentSetupGuide } from "./payment-setup";
import { BankTransferSettings } from "./bank-transfer";
import type { Settings } from "@/lib/catalog";
import { money, durationLabel } from "@/lib/catalog";
import { Field, FormError, SubmitButton, api } from "./ui";

export function BookingPreparation({ readiness, settings, onEdit, onTab, onSaved }: { readiness: BookingReadiness; settings: Settings; onEdit: (id: string) => void; onTab: (tab: string) => void; onSaved: () => Promise<void> }) {
  const [filter, setFilter] = useState("all");
  const items = readiness.catalog.items.filter(item => filter === "all" || (filter === "prices" && item.pricePending) || (filter === "durations" && (item.durationPending || item.durationEstimated)) || (filter === "team" && item.staffMissing));
  const run = readiness.reminders.lastRun;
  return <div className="booking-preparation">
    <p className="muted">Préparez l’ouverture des réservations, puis retrouvez ici les points à vérifier. Les connexions configurées doivent encore être testées avant les premiers encaissements.</p>
    <div className="preparation-grid">
      <section className="admin-panel"><CreditCard size={25}/><h2>{readiness.payment.provider === "bank_transfer" ? "Acompte par virement" : ["sumup", "mollie"].includes(readiness.payment.provider) ? "Carte bancaire & Apple Pay" : "Acompte PayPal"} · 10 €</h2><span className={`status-pill ${readiness.payment.configured ? "confirmed" : "pending_payment"}`}>{!readiness.payment.configured ? "À configurer" : readiness.payment.mode === "manual" ? "Vérification par le salon" : readiness.payment.mode === "live" ? "Configuration présente" : "Mode test configuré"}</span><p>La réservation devient confirmée uniquement après vérification de l’acompte. Le solde est réglé au salon.</p><PaymentSetupGuide payment={readiness.payment}/></section>
      <section className="admin-panel"><Mail size={25}/><h2>Confirmations et rappels</h2><span className={`status-pill ${readiness.email.configured ? "confirmed" : "pending_payment"}`}>{readiness.email.configured ? "Service d’envoi configuré" : "Envoi à activer"}</span><p>{settings.confirmationEmail ? "Confirmation prévue après réservation confirmée." : "Confirmations désactivées."} {settings.reminderEmail ? `Rappel prévu ${settings.reminderHours} h avant le rendez-vous.` : "Rappels désactivés."}</p><p className="small muted">{!settings.reminderEmail ? "Le rappel automatique est désactivé." : readiness.reminders.recent ? "La tâche automatique a été observée récemment." : !readiness.reminders.secretConfigured ? "L’envoi automatique reste à configurer sur l’hébergeur." : "La configuration est présente ; aucun passage récent de la tâche automatique n’est confirmé."}</p>{run && <p className="small muted">Dernier passage : {new Intl.DateTimeFormat("fr-FR", { dateStyle: "short", timeStyle: "short", timeZone: "Europe/Paris" }).format(new Date(run.at))} · {run.sent} envoyé(s), {run.failed} échec(s).</p>}<button className="text-link" onClick={() => onTab("settings")}>Régler les messages et les rappels</button></section>
      <section className="admin-panel"><Users size={25}/><h2>Équipe et planning</h2><p><strong>{readiness.team.count}</strong> ressource(s) active(s) · pause de <strong>{settings.bookingBufferMinutes} min</strong> entre deux rendez-vous d’une même coiffeuse.</p>{readiness.team.genericResource && <p className="small muted">« Équipe du salon » représente une seule place dans le planning. Remplacez-la par les coiffeuses réelles pour refléter votre capacité.</p>}<div className="preparation-actions"><button className="text-link" onClick={() => onTab("employees")}>Gérer les coiffeuses</button><button className="text-link" onClick={() => onTab("planning")}>Horaires et absences</button></div></section>
    </div>
    <section className="admin-panel"><Scissors size={25}/><h2>Prestations à vérifier</h2><p>{readiness.catalog.pricesPending} tarif(s), {readiness.catalog.durationsPending} durée(s) à confirmer, {readiness.catalog.durationsEstimated} durée(s) estimée(s) pour le planning et {readiness.catalog.staffMissing} variante(s) sans coiffeuse attribuée. Vos photos et tarifs existants sont conservés.</p><Field label="Afficher les points à vérifier"><select value={filter} onChange={e => setFilter(e.target.value)}><option value="all">Tous</option><option value="prices">Tarifs</option><option value="durations">Durées</option><option value="team">Attribution à l’équipe</option></select></Field><div className="preparation-review-list">{items.length ? items.map(item => <article key={`${item.serviceId}-${item.variantId}`}><div><h3>{item.name}</h3><p>{item.label} · {money(item.price)} · {durationLabel(item.duration)}{item.durationEstimated ? " environ" : ""}</p><div className="preparation-tags">{item.pricePending && <span>Tarif à valider</span>}{item.durationPending ? <span>Durée à confirmer</span> : item.durationEstimated && <span>Durée estimée</span>}{item.staffMissing && <span>Coiffeuse à attribuer</span>}</div></div><button className="button outline" onClick={() => item.staffMissing && !item.pricePending && !item.durationPending ? onTab("employees") : onEdit(item.serviceId)}>Vérifier {item.name}</button></article>) : <p className="muted">Aucun point à vérifier dans ce filtre.</p>}</div></section>
    <BankTransferSettings settings={settings} activeProvider={readiness.payment.provider} onSaved={onSaved}/>
    <NotificationSettings settings={settings} onSaved={onSaved}/>
  </div>;
}

export function NotificationSettings({ settings, onSaved }: { settings: Settings; onSaved: () => Promise<void> }) {
  const [draft, setDraft] = useState(settings); const [pending, setPending] = useState(false); const [error, setError] = useState("");
  useEffect(() => { setDraft(settings); }, [settings]);
  async function save(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setPending(true); setError("");
    try { await api("/api/admin/settings", { method: "PUT", body: JSON.stringify(draft) }); await onSaved(); }
    catch (e) { setError((e as Error).message); } finally { setPending(false); }
  }
  return <form className="admin-panel" onSubmit={save}><Clock3 size={25}/><h2>Préparer la visite et les e-mails</h2><label className="checkbox-line"><input type="checkbox" checked={draft.confirmationEmail} onChange={e => setDraft({ ...draft, confirmationEmail: e.target.checked })}/><span>Envoyer un e-mail de confirmation</span></label><label className="checkbox-line"><input type="checkbox" checked={draft.reminderEmail} onChange={e => setDraft({ ...draft, reminderEmail: e.target.checked })}/><span>Envoyer un rappel avant le rendez-vous</span></label><div className="form-grid"><Field label="Rappel avant le rendez-vous (heures)"><input type="number" min={1} max={168} disabled={!draft.reminderEmail} value={draft.reminderHours} onChange={e => setDraft({ ...draft, reminderHours: Number(e.target.value) })}/></Field><Field label="Pause entre deux clientes (minutes)"><input type="number" min={0} max={120} value={draft.bookingBufferMinutes} onChange={e => setDraft({ ...draft, bookingBufferMinutes: Number(e.target.value) })}/></Field></div><Field label="Consignes avant le rendez-vous"><textarea maxLength={2000} rows={5} value={draft.bookingInstructions} onChange={e => setDraft({ ...draft, bookingInstructions: e.target.value })} placeholder="Vos consignes : préparation des cheveux, mèches à apporter, retards et annulation…"/></Field><p className="small muted">Ces consignes apparaissent dans la réservation et dans les e-mails. Les rappels non envoyés sont recalculés après modification. Les messages déjà envoyés sont conservés. Le service d’envoi et sa tâche automatique doivent être activés.</p><FormError error={error}/><SubmitButton pending={pending}>Enregistrer les consignes et rappels</SubmitButton></form>;
}
