"use client";
import Link from "next/link";
import { useRef, useState } from "react";
import { Search, X, ArrowUpRight, Clock3, ChevronDown } from "lucide-react";
import type { Service } from "@/lib/catalog";
import { money, durationLabel, servicePrice, canBookService, canBookVariant, hasKnownDuration, durationIsEstimated, priceIsVerified } from "@/lib/catalog";
import { useSite } from "./provider";
import { Photo } from "./photo";
import { Reveal } from "./reveal";
import { ChoiceGroup } from "./ui";
export function PricingNotice({ service, variantId }: { service?: Service; variantId?: string }) {
  const { catalog } = useSite();
  const variant = service?.variants.find(variant => variant.id === variantId) || service?.variants[0];
  const verified = service && variant && priceIsVerified(service, variant);
  const durationNote = service && variant ? (!durationIsEstimated(service, variant) ? "Durée issue du calendrier du salon." : canBookVariant(service, variant) ? "Durée estimée d’après une coiffure similaire ; elle peut varier selon vos cheveux et les finitions." : "Durée à confirmer auprès du salon.") : "Les durées publiées sont reprises du calendrier du salon.";
  if (catalog.settings.pricingApproved) return service && variant && durationIsEstimated(service, variant) ? <p className="pricing-notice"><span/>{durationNote}</p> : null;
  return <p className="pricing-notice"><span/>{service ? `${verified ? "Tarif de l’affiche du salon." : "Tarif à valider auprès du salon."} ${durationNote}` : `Les tarifs de l’affiche sont identifiés. Les autres tarifs restent à valider. ${durationNote}`}</p>;
}
export function ServiceCard({ service }: { service: Service }) {
  const bookable = canBookService(service);
  const durations = service.variants.filter(variant => hasKnownDuration(service, variant)).map(variant => variant.duration);
  const minimum = Math.min(...durations), maximum = Math.max(...durations);
  return <article className="service-card"><Link href={`/coiffures/${service.id}`} className="service-card-image"><Photo src={service.image} alt={service.name} fit="contain" sizes="(max-width: 700px) 95vw, 30vw"/><span className="service-category">{service.category}</span></Link><div className="service-card-body"><div className="service-card-title"><h2><Link href={`/coiffures/${service.id}`}>{service.name}</Link></h2><ArrowUpRight size={20}/></div><p>{service.description}</p><p className="service-duration"><Clock3 size={15}/>{durations.length ? `${durationLabel(minimum)}${maximum !== minimum ? ` à ${durationLabel(maximum)}` : ""}${service.variants.some(variant => durationIsEstimated(service, variant)) ? " environ" : ""}` : "Durée à confirmer"}</p><div className="service-card-footer"><span>{service.quoteOnly ? "Sur devis" : <><small>À partir de</small><strong>{money(servicePrice(service))}</strong></>}</span><Link href={bookable ? `/reservation?prestation=${service.id}` : "/contact"} className="text-link">{bookable ? "Réserver" : "Nous contacter"}<ArrowUpRight size={17}/></Link></div></div></article>;
}
export function CataloguePage({ category: initialCategory = "Toutes" }: { category?: string }) {
  const { catalog } = useSite(); const [category, setCategory] = useState(initialCategory); const [search, setSearch] = useState("");
  const searchRef = useRef<HTMLInputElement>(null);
  const resetFilters = () => { setCategory("Toutes"); setSearch(""); searchRef.current?.focus(); };
  const categories = ["Toutes", ...new Set(catalog.services.map(item => item.category))];
  const fold = (value: string) => value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
  const words = fold(search).trim().split(/\s+/).filter(Boolean);
  const filtered = catalog.services.filter(item => {
    const searchable = fold([item.name, item.description, item.category, ...item.variants.flatMap(variant => [variant.size, variant.length])].join(" "));
    return (category === "Toutes" || item.category === category) && words.every(word => searchable.includes(word));
  });
  return <><section className="page-heading"><div className="container"><p className="eyebrow">Le catalogue du salon</p><h1>Une coiffure.<br/><em>Mille façons d’être vous.</em></h1><p>Explorez nos prestations, personnalisez votre style et trouvez votre prochain rendez-vous.</p></div></section><section className="section cream"><div className="container"><PricingNotice/><div className="catalog-toolbar"><label className="search-box"><Search size={18} aria-hidden="true"/><input ref={searchRef} type="search" enterKeyHint="search" autoComplete="off" aria-label="Rechercher une coiffure" placeholder="Coiffure, taille, longueur…" value={search} onChange={event => setSearch(event.target.value)}/>{search && <button type="button" className="search-clear" aria-label="Effacer la recherche" onClick={() => { setSearch(""); searchRef.current?.focus(); }}><X size={17}/></button>}</label><div className="filter-row">{categories.map(item => <button className={`filter-chip ${category === item ? "selected" : ""}`} aria-pressed={category === item} key={item} onClick={() => setCategory(item)}>{item}</button>)}</div></div><div className="catalog-results"><p className="results-count" aria-live="polite">{filtered.length} prestation{filtered.length > 1 ? "s" : ""}{category !== "Toutes" ? ` · ${category}` : ""}</p>{(search || category !== "Toutes") && <button type="button" className="reset-filters" onClick={resetFilters}>Réinitialiser les filtres</button>}</div><Reveal className="service-grid" stagger>{filtered.map(service => <ServiceCard key={service.id} service={service}/>)}</Reveal>{!filtered.length && <div className="empty-state"><p>Aucune coiffure ne correspond à votre recherche.</p><button className="button outline" onClick={resetFilters}>Voir toutes les coiffures</button></div>}</div></section></>;
}
export function Customise({ service, variantId, optionIds, onVariant, onOptions }: { service: Service; variantId: string; optionIds: string[]; onVariant: (id: string) => void; onOptions: (ids: string[]) => void }) {
  const variant = service.variants.find(item => item.id === variantId) || service.variants[0];
  const sizes = [...new Set(service.variants.map(item => item.size))];
  const lengths = [...new Set(service.variants.filter(item => item.size === variant.size).map(item => item.length))];
  return <div className="customise-fields">{sizes.length > 1 && <ChoiceGroup label={service.choiceLabel || (service.category === "Enfants" ? "Âge" : "Taille des tresses")}><div className="choice-row">{sizes.map(size => <button type="button" key={size} className={`choice ${variant.size === size ? "selected" : ""}`} aria-pressed={variant.size === size} onClick={() => onVariant((service.variants.find(item => item.size === size && item.length === variant.length) || service.variants.find(item => item.size === size))!.id)}>{size}</button>)}</div></ChoiceGroup>}{lengths.length > 1 && <ChoiceGroup label="Longueur"><div className="choice-row">{lengths.map(length => <button type="button" key={length} className={`choice ${variant.length === length ? "selected" : ""}`} aria-pressed={variant.length === length} onClick={() => onVariant(service.variants.find(item => item.size === variant.size && item.length === length)!.id)}>{length}</button>)}</div></ChoiceGroup>}{service.options.length > 0 && <ChoiceGroup label="La touche qui vous ressemble"><div className="option-grid">{service.options.map(option => <label className={`option-choice ${optionIds.includes(option.id) ? "selected" : ""}`} key={option.id}><input type="checkbox" checked={optionIds.includes(option.id)} onChange={event => onOptions(event.target.checked ? [...optionIds.filter(id => !option.exclusiveGroup || service.options.find(item => item.id === id)?.exclusiveGroup !== option.exclusiveGroup), option.id] : optionIds.filter(id => id !== option.id))}/><span>{option.label}</span><strong>+ {money(option.price)}</strong></label>)}</div></ChoiceGroup>}<p className="small muted">{service.hairNote || (service.hairIncluded ? "Mèches incluses." : "Mèches non incluses. Préparez vos mèches ou contactez le salon pour être conseillé·e.")}</p></div>;
}
export function ServiceDetail({ service }: { service: Service }) {
  const [variantId, setVariant] = useState(service.variants[0].id); const [options, setOptions] = useState<string[]>([]); const { catalog } = useSite();
  const variant = service.variants.find(item => item.id === variantId)!;
  const price = variant.price + service.options.filter(item => options.includes(item.id)).reduce((s, o) => s + o.price, 0);
  const duration = variant.duration + service.options.filter(item => options.includes(item.id)).reduce((s, o) => s + o.duration, 0);
  return <><div className="container section detail-layout"><div className="detail-photo-wrap"><Photo src={variant.image || service.image} alt={service.name} className="detail-photo" fit="contain" priority/><p className="image-note">{variant.imageSource || service.imageSource || (service.pricingVerified ? "Visuel de l’affiche du salon" : "Visuel d’inspiration")}{(variant.imageLink || service.imageLink) && <> · <a href={variant.imageLink || service.imageLink} target="_blank" rel="noopener noreferrer">Voir l’inspiration sur Pinterest</a></>}</p></div><div className="service-detail"><Link href="/coiffures" className="breadcrumb">Nos coiffures / {service.category}</Link><p className="eyebrow">{service.category}</p><h1>{service.name}</h1><p className="detail-description">{service.description}</p><PricingNotice service={service} variantId={variant.id}/><div className="detail-price-row"><strong>{service.quoteOnly ? "Sur devis" : money(price)}</strong><span><Clock3 size={17}/>{hasKnownDuration(service, variant) ? `${durationLabel(duration)}${durationIsEstimated(service, variant, service.options.filter(option => options.includes(option.id))) ? " environ" : ""}` : "Durée à confirmer"}</span></div>{!service.quoteOnly && <Customise service={service} variantId={variantId} optionIds={options} onVariant={setVariant} onOptions={setOptions}/>}<Link href={canBookVariant(service, variant) ? `/reservation?prestation=${service.id}&variante=${variantId}&options=${options.join(",")}` : "/contact"} className="button primary full">{canBookVariant(service, variant) ? "Réserver cette coiffure" : "Contacter le salon"}<ArrowUpRight size={18}/></Link><p className="small muted detail-location">74 Avenue de Saint-Ouen · Paris 18e</p></div></div><section className="section cream"><div className="container"><h2 className="related-title">Vous pourriez aussi aimer.</h2><Reveal className="service-grid" stagger>{catalog.services.filter(item => item.id !== service.id && item.category === service.category).slice(0, 3).map(item => <ServiceCard key={item.id} service={item}/>)}</Reveal></div></section></>;
}
export function PricesPage() {
  const { catalog } = useSite(); const categories = [...new Set(catalog.services.map(item => item.category))];
  return <><section className="page-heading"><div className="container"><p className="eyebrow">Des prestations pensées pour vous</p><h1>Le style se choisit.<br/><em>Les tarifs se découvrent.</em></h1><p>Consultez les variantes, longueurs et options de chaque prestation.</p></div></section><section className="section cream"><div className="container prices-container"><PricingNotice/>{categories.map((category, index) => <details className="price-accordion" key={category} open={index === 0}><summary><span><small>{String(index + 1).padStart(2, "0")}</small>{category}</span><ChevronDown size={23}/></summary><div className="price-accordion-content">{catalog.services.filter(item => item.category === category).map(service => <div className="price-service" key={service.id}><div className="price-service-heading"><div className="price-service-heading-title">{service.pricingVerified && <Photo src={service.image} alt={service.name} className="price-service-photo" fit="contain" sizes="120px"/>}<h3>{service.name}<small className="price-origin">{service.pricingVerified ? "Tarifs de l’affiche du salon" : catalog.settings.pricingApproved ? "Tarifs du salon" : "Tarifs indicatifs à confirmer"}</small></h3></div><Link href={`/coiffures/${service.id}`} className="text-link">{service.quoteOnly ? "Demander un devis" : canBookService(service) ? "Personnaliser & réserver" : "Voir les détails"}<ArrowUpRight size={16}/></Link></div>{service.quoteOnly ? <p>Sur devis. Contactez le salon pour une prestation personnalisée.</p> : <div className="table-scroll"><table className="price-table"><thead><tr><th>Taille / variante</th><th>Longueur</th><th>Durée</th><th>Tarif</th></tr></thead><tbody>{service.variants.map(variant => <tr key={variant.id}><td>{variant.size}</td><td>{variant.length}</td><td>{hasKnownDuration(service, variant) ? `${durationLabel(variant.duration)}${durationIsEstimated(service, variant) ? " environ" : ""}` : "À confirmer"}</td><td>{money(variant.price)}{!catalog.settings.pricingApproved && !priceIsVerified(service, variant) && <small className="price-origin">Tarif à valider</small>}</td></tr>)}</tbody></table></div>}<p className="small muted">{service.hairNote || (service.hairIncluded ? "Mèches incluses." : "Mèches non incluses.")}{service.options.length ? ` Options : ${service.options.map(item => `${item.label} +${money(item.price)}`).join(" · ")}` : ""}</p></div>)}</div></details>)}</div></section></>;
}
