import { getSettings } from "@/lib/db";
import Link from "next/link";
export async function LegalPage({ kind }: { kind: "mentions" | "privacy" | "terms" | "booking" }) {
  const settings = await getSettings();
  const titles = { mentions: "Mentions légales", privacy: "Politique de confidentialité", terms: "Conditions de commande", booking: "Politique de réservation" };
  return <section className="section cream"><div className="container legal-content"><p className="eyebrow">Fashion Afro Braids Paris</p><h1>{titles[kind]}</h1><p className="pricing-notice">Document de travail à compléter et valider par le salon avant la mise en ligne publique.</p>
    {kind === "mentions" && <><h2>Éditeur</h2><p>{settings.legalName || "Raison sociale : à renseigner par le salon."}<br/>{settings.address}<br/>SIRET : {settings.siret || "à renseigner"}<br/>Téléphone : {settings.phone}<br/>E-mail : {settings.legalEmail || "à renseigner"}</p><h2>Responsable de publication et hébergement</h2><p>Responsable de publication et coordonnées de l’hébergeur : à renseigner avant publication.</p><h2>Visuels</h2><p>Les portraits d’inspiration de la version initiale sont des images générées, identifiées comme telles. Les photos de réalisations et du salon doivent être ajoutées avec l’accord des personnes photographiées.</p></>}
    {kind === "privacy" && <><h2>Données utilisées</h2><p>Lors d’une réservation ou d’une commande, nous enregistrons votre nom, adresse e-mail, numéro de téléphone et les informations nécessaires au traitement de votre demande. Les messages envoyés par le formulaire de contact sont également enregistrés.</p><h2>Finalités et destinataires</h2><p>Ces informations servent à organiser vos rendez-vous, préparer vos commandes et répondre à vos messages. Elles sont accessibles à la personne responsable du salon. Lorsque les services correspondants sont activés, l’envoi d’e-mails est confié à Resend et les paiements à PayPal. Le site n’enregistre pas vos coordonnées bancaires.</p><h2>Conservation et droits</h2><p>La durée de conservation et l’identité du responsable de traitement doivent être définies par le salon avant l’ouverture publique. Vous pouvez demander l’accès, la rectification ou la suppression de vos données en contactant le salon au {settings.phone}{settings.legalEmail ? ` ou à ${settings.legalEmail}` : ""}.</p><h2>Stockage sur votre appareil</h2><p>Le panier et les liens privés de vos rendez-vous sont conservés dans le stockage local de votre navigateur. Le cookie de gestion sert uniquement à authentifier l’administration. Aucun outil publicitaire ou de mesure d’audience n’est installé dans cette version.</p><h2>Services externes</h2><p>La carte Google Maps n’est chargée que lorsque vous choisissez de l’afficher. Les liens vers Google Maps et les réseaux sociaux ouvrent les services correspondants, soumis à leurs propres politiques.</p></>}
    {kind === "terms" && <><h2>Produits et prix</h2><p>Les prix sont affichés en euros. Les modèles, caractéristiques, stocks, régime de TVA et conditions commerciales doivent être validés par le salon. Les commandes sont possibles uniquement pour les quantités indiquées disponibles.</p><h2>Commande et paiement</h2><p>Cette version propose une commande avec retrait au salon et paiement sur place. Aucun paiement en ligne ni livraison à domicile n’est activé pour la boutique. Une référence de commande est fournie après enregistrement.</p><h2>Retrait</h2><p>Contactez le salon au {settings.phone} pour convenir du retrait au {settings.address}. Les délais de préparation et de conservation des commandes doivent être définis par le salon.</p><h2>Réclamations, garanties et rétractation</h2><p>Les dispositions applicables, garanties légales, conditions de rétractation ou leurs exceptions, procédure de retour et coordonnées du médiateur de la consommation doivent être complétées et validées avant l’ouverture commerciale.</p></>}
    {kind === "booking" && <><h2>Choix de la prestation</h2><p>Le prix et la durée dépendent de la prestation, de la taille, de la longueur et des options choisies. Les tarifs issus de l’affiche du salon sont identifiés. Les autres tarifs et les durées estimées sont à confirmer. Lorsque les mèches ne sont pas incluses, cette information est indiquée avant réservation.</p><h2>Disponibilités</h2><p>Les horaires sont exprimés à l’heure de Paris. La durée complète de la prestation est réservée auprès d’une coiffeuse disponible. Une confirmation et une référence sont affichées après enregistrement.</p><h2>Paiement et acompte</h2><p>Un acompte de 10 € est demandé pour confirmer la réservation en ligne, selon la règle affichée pour la prestation. Il est déduit du montant total ; le solde se règle au salon. Le créneau est retenu 35 minutes pendant le paiement sécurisé PayPal. La réservation n’est confirmée qu’après vérification du paiement. L’option carte bancaire sur la page PayPal dépend de l’éligibilité du compte et du client.</p><h2>Annulation et modification</h2><p>Utilisez votre lien privé pour annuler un rendez-vous à venir sans acompte. Pour déplacer un rendez-vous ou gérer un acompte déjà versé, contactez le salon au {settings.phone}. Les règles de retard, d’annulation, de remboursement et les éventuelles pénalités doivent être définies par le salon avant l’ouverture publique.</p><h2>Confirmation et rappels</h2><p>Conservez votre lien de confirmation ou ajoutez le rendez-vous à votre calendrier. L’envoi des e-mails et rappels nécessite l’activation du service d’envoi par le salon.</p></>}
    <Link href="/contact" className="text-link">Contacter le salon →</Link></div></section>;
}
