"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Plus, Minus, Trash2, ShoppingBag, ArrowUpRight, PackageCheck, ShieldCheck, CheckCircle2, Copy } from "lucide-react";
import type { Product } from "@/lib/catalog";
import { money } from "@/lib/catalog";
import type { Order } from "@/lib/domain";
import { useSite } from "./provider";
import { Photo } from "./photo";
import { Modal, Field, SubmitButton, FormError, api } from "./ui";
import { SectionTitle } from "./home";

export function ProductCard({ product }: { product: Product }) {
  const { add } = useSite(); const [quantity, setQuantity] = useState(1); const [details, setDetails] = useState(false);
  return <article className="product-card"><button className="product-image-button" onClick={() => setDetails(true)} aria-label={`Voir ${product.name}`}><Photo src={product.image} alt={product.name} sizes="(max-width: 700px) 45vw, 25vw"/>{!product.stock && <span className="product-badge">Bientôt disponible</span>}</button><div className="product-info"><p className="product-category">{product.category}</p><div className="product-name-row"><button onClick={() => setDetails(true)}><h3>{product.name}</h3></button><strong>{money(product.price)}</strong></div><p className="product-size">{product.size}</p><div className="product-add-row"><div className="quantity"><button disabled={quantity <= 1} aria-label={`Réduire la quantité de ${product.name}`} onClick={() => setQuantity(q => q - 1)}><Minus size={13}/></button><span>{quantity}</span><button disabled={quantity >= Math.min(product.stock, 10)} aria-label={`Augmenter la quantité de ${product.name}`} onClick={() => setQuantity(q => q + 1)}><Plus size={13}/></button></div><button className="add-to-cart" disabled={!product.stock} onClick={() => add(product, quantity)}><Plus size={15}/>{product.stock ? "Ajouter" : "Indisponible"}</button></div></div><Modal open={details} onClose={() => setDetails(false)} title={product.name}><Photo src={product.image} alt={product.name} className="product-detail-photo"/><p>{product.description}</p><p className="muted">{product.size}</p><p className="product-detail-price">{money(product.price)}</p><p className="small muted">Visuel repris du site actuel ; modèle exact à confirmer.</p><button className="button primary full" disabled={!product.stock} onClick={() => { add(product, quantity); setDetails(false); }}>{product.stock ? "Ajouter au panier" : "Stock à renseigner par le salon"}<Plus size={18}/></button></Modal></article>;
}
export function CartDrawer() {
  const { cartOpen, setCartOpen, cart, catalog, update } = useSite();
  const lines = cart.map(item => ({ ...item, product: catalog.products.find(product => product.id === item.productId) }));
  const total = lines.reduce((sum, item) => sum + (item.product?.price || 0) * item.quantity, 0);
  return <Modal open={cartOpen} onClose={() => setCartOpen(false)} title="Votre panier" className="cart-modal">{lines.length ? <><div className="cart-lines">{lines.map(item => <div key={item.productId} className="cart-line"><Photo src={item.product?.image || "/images/beads.svg"} alt={item.product?.name || "Produit indisponible"}/><div><h3>{item.product?.name || "Produit indisponible"}</h3><p>{money(item.product?.price || 0)}</p><div className="quantity"><button aria-label="Diminuer" onClick={() => update(item.productId, item.quantity - 1)}><Minus size={14}/></button><span>{item.quantity}</span><button aria-label="Augmenter" disabled={item.quantity >= Math.min(item.product?.stock || 0, 10)} onClick={() => update(item.productId, item.quantity + 1)}><Plus size={14}/></button></div>{(!item.product || item.quantity > item.product.stock) && <p className="form-error small">Stock insuffisant</p>}</div><button className="icon-button" onClick={() => update(item.productId, 0)} aria-label={`Retirer ${item.product?.name || "le produit"}`}><Trash2 size={17}/></button></div>)}</div><div className="cart-total"><span>Sous-total</span><strong>{money(total)}</strong></div><p className="muted small">Retrait au salon gratuit. Paiement sur place.</p><Link href="/commande" onClick={() => setCartOpen(false)} className="button primary full">Passer la commande <ArrowUpRight size={18}/></Link><Link href="/boutique" onClick={() => setCartOpen(false)} className="continue-shopping">Continuer mes achats</Link></> : <div className="empty-state"><ShoppingBag size={40} strokeWidth={1}/><h3>Un peu de douceur pour vos cheveux ?</h3><p>Votre panier attend vos essentiels.</p><Link href="/boutique" onClick={() => setCartOpen(false)} className="button primary">Découvrir la boutique <ArrowUpRight size={17}/></Link></div>}</Modal>;
}
export function ShopPage() {
  const { catalog } = useSite(); const [category, setCategory] = useState("Tous");
  return <><section className="page-heading"><div className="container"><p className="eyebrow">La sélection Fashion Afro Braids</p><h1>Vos essentiels.<br/><em>Votre beauté au quotidien.</em></h1><p>Prolongez l’expérience du salon, à la maison.</p></div></section><section className="section cream"><div className="container"><div className="shop-benefits"><span><PackageCheck size={18}/>Retrait au salon</span><span><ShieldCheck size={18}/>Paiement sur place</span><span><MapPinIcon/>Paris 18e</span></div><div className="filter-row">{["Tous", ...new Set(catalog.products.map(item => item.category))].map(item => <button className={`filter-chip ${category === item ? "selected" : ""}`} aria-pressed={category === item} key={item} onClick={() => setCategory(item)}>{item}</button>)}</div><div className="product-grid">{catalog.products.filter(item => category === "Tous" || category === item.category).map(product => <ProductCard key={product.id} product={product}/>)}</div><p className="image-note">Visuels repris du site actuel. Les stocks et modèles exacts seront renseignés par le salon avant l’ouverture des commandes.</p></div></section></>;
}
function MapPinIcon() { return <span aria-hidden="true">◈</span>; }
export function Checkout() {
  const { cart, ready, catalog, clear, refresh } = useSite(); const router = useRouter(); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const [requestId] = useState(() => typeof crypto !== "undefined" && crypto.randomUUID ? crypto.randomUUID() : "");
  const lines = cart.map(item => ({ ...item, product: catalog.products.find(product => product.id === item.productId) }));
  const total = lines.reduce((sum, item) => sum + (item.product?.price || 0) * item.quantity, 0);
  const invalid = lines.some(item => !item.product || item.quantity > item.product.stock);
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (pending) return; setPending(true); setError("");
    const data = new FormData(event.currentTarget);
    try {
      const order = await api<{ id: string; token: string }>("/api/orders", { method: "POST", body: JSON.stringify({ name: `${data.get("firstName")} ${data.get("lastName")}`.trim(), email: data.get("email"), phone: data.get("phone"), consent: data.get("consent") === "on", items: cart, requestId: requestId || crypto.randomUUID() }) });
      clear(); await refresh(); router.push(`/commande/${order.id}?token=${encodeURIComponent(order.token)}`);
    } catch (error) { setError((error as Error).message); await refresh(); } finally { setPending(false); }
  }
  if (!ready) return <div className="container section">Chargement de votre panier…</div>;
  if (!cart.length) return <div className="container section empty-state"><ShoppingBag size={42}/><h1>Votre panier est vide</h1><Link href="/boutique" className="button primary">Découvrir la boutique <ArrowUpRight size={18}/></Link></div>;
  return <div className="container section checkout-layout"><div><p className="eyebrow">La dernière étape</p><h1>Vos essentiels,<br/><em>à retrouver au salon.</em></h1><form onSubmit={submit} className="form-panel"><h2>Vos coordonnées</h2><div className="form-grid"><Field label="Prénom"><input name="firstName" required autoComplete="given-name" maxLength={50}/></Field><Field label="Nom"><input name="lastName" required autoComplete="family-name" maxLength={50}/></Field><Field label="E-mail"><input name="email" type="email" required autoComplete="email"/></Field><Field label="Téléphone"><input name="phone" type="tel" required autoComplete="tel"/></Field></div><div className="pickup-card"><PackageCheck size={25}/><div><strong>Retrait au salon · gratuit</strong><p>{catalog.settings.address}</p><p>Le salon vous contacte pour organiser le retrait. Le paiement se fait sur place.</p></div></div><label className="checkbox-line"><input name="consent" type="checkbox" required/><span>J’accepte les <Link href="/cgv" target="_blank">conditions de commande</Link> et l’utilisation de mes coordonnées pour cette commande, conformément à la <Link href="/confidentialite" target="_blank">politique de confidentialité</Link>.</span></label><FormError error={error || (invalid ? "Un produit n’est plus disponible en quantité suffisante. Modifiez votre panier." : "")}/><SubmitButton pending={pending} disabled={invalid} className="button primary full">Confirmer ma commande · {money(total)}</SubmitButton><p className="small muted">Aucun prélèvement en ligne. Commande avec paiement au salon.</p></form></div><aside className="summary-card"><p className="eyebrow">Votre sélection</p>{lines.map(item => <div className="checkout-line" key={item.productId}><Photo src={item.product?.image || "/images/beads.svg"} alt={item.product?.name || "Produit"}/><div><strong>{item.product?.name}</strong><p>Quantité : {item.quantity}</p></div><span>{money((item.product?.price || 0) * item.quantity)}</span></div>)}<div className="summary-total"><span>Sous-total</span><strong>{money(total)}</strong></div><div className="summary-row"><span>Livraison</span><span>Retrait gratuit</span></div><div className="summary-total"><span>Total</span><strong>{money(total)}</strong></div></aside></div>;
}
export function OrderConfirmation({ order }: { order: Order }) {
  const { catalog, toast } = useSite();
  return <div className="container section confirmation-page"><span className="confirmation-icon"><CheckCircle2 size={38} strokeWidth={1.5}/></span><p className="eyebrow">Merci pour votre commande</p><h1>{order.status === "cancelled" ? "Commande annulée." : "Vos essentiels vous attendent."}</h1><p>Référence : <strong>{order.id}</strong></p><div className="confirmation-card"><p className="status-pill">{order.status === "completed" ? "Retirée au salon" : order.status === "cancelled" ? "Annulée" : "En attente de retrait"}</p>{order.data.items.map(item => <div className="summary-row" key={item.productId}><span>{item.name} × {item.quantity}</span><strong>{money(item.price * item.quantity)}</strong></div>)}<div className="summary-total"><span>Total à payer sur place</span><strong>{money(order.data.total)}</strong></div><div className="pickup-card"><PackageCheck size={24}/><div><strong>Retrait au salon</strong><p>{catalog.settings.address}</p><p>Contactez le salon pour convenir du retrait : <a href={`tel:${catalog.settings.phone.replace(/\s/g, "")}`}>{catalog.settings.phone}</a>.</p></div></div></div><div className="confirmation-actions"><button className="button outline" onClick={async () => { try { await navigator.clipboard.writeText(window.location.href); toast("Lien de suivi copié"); } catch { toast("Enregistrez cette page dans vos favoris."); } }}><Copy size={17}/>Conserver mon lien de suivi</button><Link href="/boutique" className="button primary">Retour à la boutique <ArrowUpRight size={17}/></Link></div></div>;
}
