import Link from "next/link";
import { ArrowUpRight, Heart, Scissors } from "lucide-react";
import { Photo } from "@/components/photo";
import { getSettings, all } from "@/lib/db";
import type { GalleryPhoto } from "@/lib/catalog";
export const metadata = { title: "Notre salon · L’expertise afro à Paris" };
export default async function Page() {
  const settings = await getSettings(); const salonPhoto = (await all<GalleryPhoto>("gallery")).find(item => item.active && item.category === "Salon");
  return <><section className="page-heading"><div className="container"><p className="eyebrow">Fashion Afro Braids Paris</p><h1>La passion du geste.<br/><em>La beauté du résultat.</em></h1></div></section><section className="section cream"><div className="container about-layout"><div><Photo src={salonPhoto?.image || "/images/acuity-85576228.jpg"} alt={salonPhoto ? "Le salon Fashion Afro Braids" : "Knotless Small · catalogue du salon"} className="about-photo" priority/><p className="image-note">{salonPhoto ? salonPhoto.title : "Visuel du catalogue fourni par le salon"}</p></div><div className="about-copy"><p className="eyebrow">Votre salon à Paris 18e</p><h2>Votre beauté,<br/><em>notre inspiration.</em></h2><p>Bienvenue chez Fashion Afro Braids, votre salon spécialisé dans la coiffure afro à Paris. Notre mission est de révéler votre beauté à travers des coiffures modernes, élégantes et réalisées avec passion.</p><p>Tresses, knotless, extensions, tissages, perruques et soins : nous vous accompagnons dans le choix d’un style adapté à vos envies et à vos cheveux.</p><p>Un nouveau look, l’entretien de votre coiffure ou une occasion particulière : chaque rendez-vous est une rencontre, chaque coiffure une expression de votre personnalité.</p><div className="about-facts"><div><strong>Paris 18e</strong><span>Avenue de Saint-Ouen</span></div><div><strong>Expertise afro</strong><span>Tresses, soins & textures</span></div></div><Link href="/reservation" className="button primary">Prenons rendez-vous <ArrowUpRight size={18}/></Link></div></div></section><section className="about-quote"><div className="container"><Scissors size={28} strokeWidth={1}/><h2>« Une coiffure qui vous ressemble,<br/><em>un moment qui vous appartient. »</em></h2><span>La philosophie Fashion Afro Braids</span></div></section></>;
}
